// defining and initializing variables
let randomNumber, usersInput, humanChoice, computerChoice, computerScore=0, yourScore=0;

// defining function to generate a random computer and print the generated value to the console
function getComputerChoice () {
    randomNumber = Math.floor(Math.random()*100) // Math.floor() is used to round off the value generated by Math.random() i.e. a random value between 0 and 1(not including) which is later multiplied by 100 to give a random value between 0 to 100(not including)
    if (randomNumber <= 33) {
       return "ROCK";
    } else if (randomNumber > 66) {
        return "SCISSOR";
    } else {
        return "PAPER";
    }
}

// defining function to get input from user with prompt command and to print the received input to the console
function getHumanChoice () {

    usersInput = (prompt("Enter your Selection among Rock, Paper and Scissor")).toUpperCase(); // input received is in-case sensitivised with the help of string.toUpperCase(), therefore, irrespective of whatever case the user inputs the value in, it can be easily compared as every input is converted to Uppercase here.
    if (usersInput === "ROCK" || usersInput === "PAPER" || usersInput === "SCISSOR") {
        return usersInput;
    } else {
        return "an Invalid Choice" // yourChoice is assigned a value invalid for the purpose of meeting the requirement of line 33.
     }
}



function playRound(humanChoice,computerChoice) {
    
    if (humanChoice === computerChoice || humanChoice === "an Invalid Choice") {
        console.log(`This round was either a tie or you have entered an invalid choice - the scroes are Computer : ${computerScore} and You : ${yourScore}`);
    } else if ((humanChoice === "ROCK" && computerChoice === "SCISSOR") || (humanChoice === "PAPER" && computerChoice === "ROCK") || (humanChoice === "SCISSOR" && computerChoice === "PAPER")) {
        yourScore = yourScore+1;
        console.log(`${humanChoice} beats ${computerChoice}!`);
        console.log(`Congratulations, you won this round! - the scores are Computer : ${computerScore} and You : ${yourScore}`);
    } else {
        computerScore = computerScore + 1;
        console.log(`${computerChoice} beats ${humanChoice}!`);
        console.log(`Sorry, you lost this round! - the scores are Computer : ${computerScore} and You : ${yourScore}`);
    }

    playGame ();

}

function playGame () {
   
    if ((computerScore+yourScore)<5) {
        humanSelection = getHumanChoice ();
        computerSelection = getComputerChoice ();
        console.log(`You Selected ${humanSelection}`)
        console.log(`Computer Selected ${computerSelection}`)
        playRound (humanSelection,computerSelection);
        
    } else if (computerScore>yourScore) {
        console.log("Game Over!");
        console.log("Sorry! You lost! Better luck next time!");
    
    } else {
        console.log("Congratulations! You won the Game")
    }
}

playGame ();