// defining and initializing variables
let randomNumber, humanChoice, computerChoice, computerScore=0, yourScore=0;

// defining function to generate a random computer and print the generated value to the console
function getComputerChoice () {
    randomNumber = Math.floor(Math.random()*100) // Math.floor() is used to round off the value generated by Math.random() i.e. a random value between 0 and 1(not including) which is later multiplied by 100 to give a random value between 0 to 100(not including)
    if (randomNumber <= 33) {
       return "ROCK";
    } else if (randomNumber > 66) {
        return "SCISSOR";
    } else {
        return "PAPER";
    }
}

buttons = document.querySelectorAll("button");

for (const button of buttons) {
    button.addEventListener('click', () => { 
    humanSelection = button.textContent;
    computerSelection = getComputerChoice();
    playRound(humanSelection,computerSelection);
    
})
}

function playRound(humanChoice,computerChoice) { 

    const human = document.querySelector('#humanChoice');
    const comp = document.querySelector('#computerChoice');
    const winner = document.querySelector('#winner');
    const scores = document.querySelector('#scores');
    const final = document.querySelector('#finalWinner');
    human.textContent = `You Selected ${humanChoice}`; 
    comp.textContent = `Computer Selected ${computerChoice}`;
    if (yourScore === 5) {
        final.textContent = "Congratulations! You won this game."
        human.textContent = "";
        comp.textContent = "";
        winner.textContent = "";
        yourScore = 0;
        computerScore = 0;
    } else if (computerScore === 5) {
        final.textContent = "Sorry! You lost this game. Better luck next time."
        yourScore = 0;
        computerScore = 0;
        human.textContent = "";
        comp.textContent = "";
        winner.textContent = "";
    } else {
        final.textContent = "";
         if (humanChoice === computerChoice) {
            winner.textContent = `Nobody wins!`
            scores.textContent = `The scroes are Computer : ${computerScore} and You : ${yourScore}`
        } else if ((humanChoice === "ROCK" && computerChoice === "SCISSOR") 
            || (humanChoice === "PAPER" && computerChoice === "ROCK") 
            || (humanChoice === "SCISSOR" && computerChoice === "PAPER")) {
            yourScore = yourScore+1;
            winner.textContent = `Congratulations! you won this round as ${humanChoice} beats ${computerChoice}!`
            scores.textContent = `The scores are Computer : ${computerScore} and You : ${yourScore}`        
            } else {
            computerScore = computerScore + 1;
            winner.textContent = `Sorry! you lost this round as {computerChoice} beats ${humanChoice}!`
            scores.textContent = `The scores are Computer : ${computerScore} and You : ${yourScore}`
        }
    }
}
