// defining and initializing variables
let randomChoice, computerChoice, yourChoice="rock", computerScore=0, yourScore=0;

const q = document.querySelector("p");
console.log(q);

// defining function to generate a random computer and print the generated value to the console
function getComputerChoice () {
    randomChoice = Math.floor(Math.random()*100) // Math.floor() is used to round off the value generated by Math.random() i.e. a random value between 0 and 1(not including) which is later multiplied by 100 to give a random value between 0 to 100(not including)
    if (randomChoice <= 33) {
      computerChoice = "ROCK";
    } else if (randomChoice > 66) {
        computerChoice = "SCISSOR";
    } else {
        computerChoice = "PAPER";
    }
    console.log(`The Computer selected ${computerChoice}`);
}

// defining function to get input from user with prompt command and to print the received input to the console
function getYourChoice () {

    yourChoice = (prompt("Enter your Selection among Rock, Paper and Scissor")).toUpperCase(); // input received is in-case sensitivised with the help of string.toUpperCase(), therefore, irrespective of whatever case the user inputs the value in, it can be easily compared as every input is converted to Uppercase here.
    if (yourChoice === "ROCK" || yourChoice === "PAPER" || yourChoice === "SCISSOR") {
        console.log(`You selected ${yourChoice}`);
    } else {
        console.log(`You selected ${yourChoice} which is invalid`);
        yourChoice = "Invalid" // yourChoice is assigned a value invalid for the purpose of meeting the requirement of line 33.
     }
}

// defining a for loop for the purpose of running the program of comparison and declaration of the winner for a total of 5 rounds.
 for(i=1; i<=5; i++) {
    console.log(`--- Round No. ${i} ---`)
    getYourChoice(); // the function for your choice is called; please note that function for Users input is called first as otherwise the computers input will be printed on the console before the user can enter his input, if the other function is called first, thereby defeating the whole purpose of the game.
    getComputerChoice(); // the function for computers choice is called
        if (yourChoice === computerChoice || yourChoice === "Invalid") {
        console.log(`This round was either a tie or you have entered an invalid choice - the scroes are Computer : ${computerScore} and You : ${yourScore}`);
        i=i-1; // when input is invalid or if there is a tie the round is not counted, as such the loop value is hereby decremented by 1.
    } else if ((yourChoice === "ROCK" && computerChoice === "SCISSOR") || (yourChoice === "PAPER" && computerChoice === "ROCK") || (yourChoice === "SCISSOR" && computerChoice === "PAPER")) {
        yourScore = yourScore+1;
        console.log(`${yourChoice} beats ${computerChoice}!`);
        console.log(`Congratulations, you won this round! - the scores are Computer : ${computerScore} and You : ${yourScore}`);
    } else {
        computerScore = computerScore + 1;
        console.log(`${computerChoice} beats ${yourChoice}!`);
        console.log(`Sorry, you lost this round! - the scores are Computer : ${computerScore} and You : ${yourScore}`);
    }
}

// conditional operators used to compare the final scores and declare the winner and print the same on the console.
if (computerScore>yourScore) {
    console.log("Sorry! you lost this game. Better luck next time!")
} else {
    console.log("Hurray! You won the game. Well played!")
}